apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "escapecloud.engineConfigMapName" . }}
  labels:
    {{- include "escapecloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: escape-engine
data:
  WEBHOOK_URL: {{ default (printf "http://%s.%s.svc.cluster.local/api/assessmentOrderWebhook" (include "escapecloud.webappName" .) .Release.Namespace) .Values.escapeEngine.env.WEBHOOK_URL | quote }}
  {{- range $key, $value := .Values.escapeEngine.env }}
  {{- if ne $key "WEBHOOK_URL" }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
