apiVersion: v1
kind: Secret
metadata:
  name: {{ include "escapecloud.webSecretName" . }}
  labels:
    {{- include "escapecloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: escape-web
type: Opaque
stringData:
  {{- range $key, $value := .Values.escapeWeb.secretEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
